return {
	-- "akinsho/bufferline.nvim",
	-- event = "VeryLazy",
	-- keys = {
	-- 	{ "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", desc = "Toggle pin" },
	-- 	{ "<leader>bP", "<Cmd>BufferLineGroupClose ungrouped<CR>", desc = "Delete non-pinned buffers" },
	-- 	{ "<S-h>", "<cmd>BufferLineCyclePrev<cr>", { desc = "Prev buffer" } },
	-- 	{ "<S-l>", "<cmd>BufferLineCycleNext<cr>", { desc = "Next buffer" } },
	-- },
	-- opts = {
	-- 	options = {
	-- 		close_command = function(n)
	-- 			require("mini.bufremove").delete(n, false)
	-- 		end,
	-- 		right_mouse_command = function(n)
	-- 			require("mini.bufremove").delete(n, false)
	-- 		end,
	-- 		diagnostics = "nvim_lsp",
	-- 		always_show_bufferline = false,
	-- 		diagnostics_indicator = function(_, _, diag)
	-- 			local icons = require("config.utils").icons.diagnostics
	-- 			local ret = (diag.error and icons.Error .. diag.error .. " " or "")
	-- 				.. (diag.warning and icons.Warn .. diag.warning or "")
	-- 			return vim.trim(ret)
	-- 		end,
	-- 		offsets = {
	-- 			{
	-- 				filetype = "neo-tree",
	-- 				text = "Neo-tree",
	-- 				highlight = "Directory",
	-- 				text_align = "left",
	-- 			},
	-- 		},
	-- 	},
	-- },
}
